[project]
name = "astro-framing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astroplan>=0.10.1",
    "astropy>=6.1.7",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pillow>=12.2.0",
    "pyobjc-framework-cocoa>=12.1; sys_platform == 'darwin'",
    "pyqt6>=6.11.0",
    "pyqtdarktheme>=2.1.0",
    "reproject>=0.14.1",
]
